### ISSUE TITLE
Typo's in the CLI text for mapping file inputs to pipeline

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-cli#14]
"please map them to the [big blank space] assay inputs"

![image](https://user-images.githubusercontent.com/317043/39431116-b8d8b64c-4c5d-11e8-914e-64c992bbaf3f.png)

**Comment by jim-bo** [comment]
Another bug in the "Available Ass [blank space] ays" title. 

![image](https://user-images.githubusercontent.com/317043/39431187-f1caa762-4c5d-11e8-90aa-629ae228f741.png)

**Comment by lemccarthy** [comment]
Fixed as of https://github.com/dfci/cidc-cli/commit/24b444bb67e7624f40ab3f31dc840679f536a4e4
