### ISSUE TITLE
entry point

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-cli#3]
We want to make this feel like a traditional command line tool so the entry point needs to be more traditional.

You can make the main tool executable by using this shebang `#!/usr/bin/env python` and making the file executable. Alternatively you can create a shell script entry point which calls the python module (maybe checkout some examples on pip).

**Comment by lemccarthy** [comment]
Fixed as of https://github.com/dfci/cidc-cli/commit/e12d0419e981db694e4b02bcfdcdc1f2eec38c75 , tool may now be installed as a package and run by name.

**Comment by jim-bo** [comment]
duplicate of #4
