### ISSUE TITLE
warning when launching command

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-cli#4]
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'interface.cli' found in sys.modules after import of package 'interface', but prior to execution of 'interface.cli'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))

**Comment by lemccarthy** [comment]
Fixed as of https://github.com/dfci/cidc-cli/commit/e12d0419e981db694e4b02bcfdcdc1f2eec38c75

**Comment by jim-bo** [comment]
Error when installing from setup.py
![image](https://user-images.githubusercontent.com/317043/37108702-e51f6624-2205-11e8-9481-7128729cd0f8.png)

**Comment by jim-bo** [comment]
closing similar ticket #3

**Comment by lemccarthy** [comment]
Fixed error as of https://github.com/dfci/cidc-cli/commit/9d43a44afc82a9127449996e4cb0d0ec0b04f878

**Comment by jim-bo** [comment]
looks good.
