### ISSUE TITLE
ModuleNotFoundError: No module named 'cidc_utils'

### ISSUE THREAD

**Issue by manugarciaquismondo** [dfci/cidc-cli#41]
After executing _cidc_cli_, the following error is prompted and the system halts:

> Traceback (most recent call last):
>   File "/home/manu/Envs/cidc-cli-3v85Tfw-/bin/cidc_cli", line 7, in <module>
>     from cli.interface.cli import main
>   File "/home/manu/Envs/cidc-cli-3v85Tfw-/lib/python3.6/site-packages/cli/interface/cli.py", line 7, in <module>
>     from cidc_utils.caching import CredentialCache
> ModuleNotFoundError: No module named 'cidc_utils'
> 

I suspect this is because the file _cidc_utils/requests.py_ inside the directory _cli_ does not exist, or it is not shared via Github.

**Comment by mtmcduffie** [comment]
I need to update Portal instructions to explain how to get the dependencies installed.
