### ISSUE TITLE
error after successful athentication

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-cli#9]
Get wonky page in chrome. Consider ascii art.

![image](https://user-images.githubusercontent.com/317043/38107306-87e2fb36-335f-11e8-84df-5413e554b1f1.png)

**Comment by lemccarthy** [comment]
Fixed in https://github.com/dfci/cidc-cli/commit/74f0c4974aaa5a5e0b7ff196f6c0423fde752cf4
